// iCorsi Course Assistant — content script
// Gira solo sulle pagine iCorsi (vedi manifest). Responsabilità:
//  1. inserire la sidebar/chatbox (Shadow DOM, per non interferire col sito)
//  2. su richiesta dell'utente ("Scansiona questa pagina") rilevare i link ai
//     materiali (PDF, pluginfile.php, mod/resource, mod/page) visibili
//  3. scaricare SOLO le risorse già accessibili con la sessione corrente
//     (fetch same-origin con credenziali: nessun bypass di login o permessi)
//  4. estrarre il testo (pdf.js per i PDF, DOM per le pagine HTML), fare il
//     chunking e inviare tutto al background per l'indicizzazione locale.

(() => {
  if (window.__icorsiAssistantLoaded) return;
  window.__icorsiAssistantLoaded = true;

  const MAX_DOCS_PER_SCAN = 20;   // anti-scraping: limite per scansione
  const MAX_SUBPAGES = 8;         // sottopagine (sezioni/cartelle) per scansione
  const FETCH_CONCURRENCY = 2;    // richieste in parallelo, volutamente basse
  const FETCH_DELAY_MS = 300;     // pausa tra un download e l'altro
  const MAX_FILE_BYTES = 30 * 1024 * 1024; // ignora file > 30 MB
  // Pattern di esclusione predefiniti: URL e titoli tipici di contenuti
  // Teams/SharePoint/LTI che non vanno indicizzati (modificabili in Settings)
  const DEFAULT_EXCLUDES = [
    'teams.microsoft',
    'sharepoint',
    'mod/lti',
    'ms teams',
    'teams meeting',
    'teams recording',
    'registrazione teams',
    'manuale panopto',
  ].join('\n');

  // -------------------------------------------------------------------------
  // i18n dell'interfaccia (default: inglese; il pulsante in alto cambia lingua)
  // -------------------------------------------------------------------------

  const I18N = {
    en: {
      appTitle: 'Course Assistant',
      fabTitle: 'Open course assistant',
      settingsTitle: 'Settings',
      close: 'Close',
      urlLabel: 'Ollama server URL:',
      modelLabel: 'Model (from Ollama):',
      modelNone: '— extractive search only —',
      refreshTitle: 'Reload the model list from Ollama',
      langLabel: 'Answer language:',
      langAuto: 'Automatic (follows the question)',
      autoScanLabel: 'Scan automatically when the course dashboard loads',
      deepScanLabel: 'Also explore subpages (sections, folders) — off: dashboard only',
      excludeLabel: 'Exclude documents (one pattern per line, matches URL or title):',
      privacy:
        'Privacy: everything stays on your machine. Documents are indexed in your browser ' +
        '(IndexedDB) and answers are generated by a local model via Ollama: no data is sent ' +
        'to external services. Without a model selected, the chat returns the most relevant ' +
        'excerpts. You can clear the index at any time.',
      embedOn:
        'Semantic search: active (nomic-embed-text). Embeddings are created during scanning: ' +
        're-scan pages to enable them on previously indexed content.',
      embedOff:
        'Semantic search: off. To enable it run "ollama pull nomic-embed-text" and reopen these settings.',
      save: 'Save',
      saved: 'Settings saved.',
      clearIndex: 'Clear index',
      cleared: 'Index cleared.',
      confirmClear: 'Delete all locally indexed documents?',
      scan: 'Scan this page',
      statsFmt: (d, c) => `${d} docs · ${c} excerpts`,
      statusScanPage: 'Indexing the text of this page…',
      statusExploreFolder: (t2) => `Exploring folder: ${t2}`,
      statusExploreSection: (t2) => `Exploring section: ${t2}`,
      statusFound: (n) => `Found ${n} linked materials.`,
      warnSubpages: (n, m) => `Found ${n} subpages: exploring only the first ${m}.`,
      warnTooMany: (n, m) => `Found ${n} materials: indexing only the first ${m}.`,
      warnNoPageText: 'No extractable text on the current page.',
      warnScanned: (t2) => `"${t2}": looks like a scanned PDF (little extractable text).`,
      removedExcluded: (n, titles) => `Removed ${n} excluded document(s) from the index: "${titles}".`,
      scanDone: (i2, u) => `Scan complete: ${i2} new or updated, ${u} unchanged.`,
      skippedLabel: (n) => `Skipped (${n}):`,
      warningsLabel: 'Warnings:',
      scanError: (m) => `Error during scan: ${m}`,
      currentPage: 'Current page',
      placeholder: 'Ask about the course materials… (Enter to send)',
      searching: '… searching the materials …',
      sourcesLabel: 'Sources:',
      pageAbbr: 'p.',
      errConn: 'Error: connection to the background was interrupted. Reload the page and retry.',
      errGeneric: (m) => `Error: ${m}`,
      noAnswer: '(no answer)',
      ollamaOk: (n) => `Ollama OK: ${n} models available.`,
      ollamaDown: 'Ollama is not reachable: make sure the app is running (see README).',
      send: 'Send',
      chipSummary: 'Summary',
      tplSummary: 'Summarize "<document>" in a structured way, with the key points.',
      chipQuiz: 'Quiz',
      tplQuiz: 'Create 10 review questions (with answers) on the contents of "<document>".',
      chipKeys: 'Key points',
      tplKeys: 'What are the most important concepts for the exam in "<document>"?',
      chipFlash: 'Flashcards',
      tplFlash:
        'Create 12 flashcards (front: question/term, back: answer/definition) from "<document>".',
      chipOral: 'Oral exam',
      tplOral:
        'Act as the professor in an oral exam on "<document>": ask me one question at a time, wait for my answer, then correct it and continue.',
      chipPlan: 'Study plan',
      tplPlan:
        'Create a study plan using the indexed materials and the visible deadlines. Exam topic: "<document>".',
      chipWeek: 'This week',
      tplWeek: 'Summarize the course materials added this week, document by document.',
      docPh: '<document>',
    },
    it: {
      appTitle: 'Assistente corso',
      fabTitle: 'Apri assistente corso',
      settingsTitle: 'Impostazioni',
      close: 'Chiudi',
      urlLabel: 'URL del server Ollama:',
      modelLabel: 'Modello (da Ollama):',
      modelNone: '— solo ricerca estrattiva —',
      refreshTitle: 'Ricarica la lista dei modelli da Ollama',
      langLabel: 'Lingua delle risposte:',
      langAuto: 'Automatica (segue la domanda)',
      autoScanLabel: 'Scansiona automaticamente quando si apre la dashboard del corso',
      deepScanLabel: 'Esplora anche le sottopagine (sezioni, cartelle) — spento: solo dashboard',
      excludeLabel: 'Escludi documenti (un pattern per riga, confrontato con URL o titolo):',
      privacy:
        'Privacy: tutto resta sulla tua macchina. I documenti sono indicizzati nel browser ' +
        '(IndexedDB) e le risposte sono generate da un modello locale via Ollama: nessun dato ' +
        'viene inviato a servizi esterni. Senza modello selezionato, la chat restituisce gli ' +
        'estratti più rilevanti. Puoi cancellare l\'indice in qualsiasi momento.',
      embedOn:
        'Ricerca semantica: attiva (nomic-embed-text). Gli embeddings vengono creati durante ' +
        'la scansione: riscansiona le pagine per abilitarli sui contenuti già indicizzati.',
      embedOff:
        'Ricerca semantica: spenta. Per attivarla esegui "ollama pull nomic-embed-text" e riapri queste impostazioni.',
      save: 'Salva',
      saved: 'Impostazioni salvate.',
      clearIndex: 'Cancella indice',
      cleared: 'Indice cancellato.',
      confirmClear: 'Cancellare tutti i documenti indicizzati localmente?',
      scan: 'Scansiona questa pagina',
      statsFmt: (d, c) => `${d} doc · ${c} estratti`,
      statusScanPage: 'Indicizzo il testo di questa pagina…',
      statusExploreFolder: (t2) => `Esploro la cartella: ${t2}`,
      statusExploreSection: (t2) => `Esploro la sezione: ${t2}`,
      statusFound: (n) => `Trovati ${n} materiali collegati.`,
      warnSubpages: (n, m) => `Trovate ${n} sottopagine: ne esploro solo le prime ${m}.`,
      warnTooMany: (n, m) => `Trovati ${n} materiali: ne indicizzo solo i primi ${m}.`,
      warnNoPageText: 'Nessun testo estraibile dalla pagina corrente.',
      warnScanned: (t2) => `"${t2}": sembra un PDF scansionato (poco testo estraibile).`,
      removedExcluded: (n, titles) => `Rimossi dall'indice ${n} documenti esclusi: "${titles}".`,
      scanDone: (i2, u) => `Scansione completata: ${i2} nuovi o aggiornati, ${u} invariati.`,
      skippedLabel: (n) => `Saltati (${n}):`,
      warningsLabel: 'Avvisi:',
      scanError: (m) => `Errore durante la scansione: ${m}`,
      currentPage: 'Pagina corrente',
      placeholder: 'Chiedi qualcosa sui materiali del corso… (Invio per inviare)',
      searching: '… sto cercando nei materiali …',
      sourcesLabel: 'Fonti:',
      pageAbbr: 'pag.',
      errConn: 'Errore: connessione col background interrotta. Ricarica la pagina e riprova.',
      errGeneric: (m) => `Errore: ${m}`,
      noAnswer: '(nessuna risposta)',
      ollamaOk: (n) => `Ollama OK: ${n} modelli disponibili.`,
      ollamaDown: 'Ollama non raggiungibile: verifica che l\'app sia in esecuzione (vedi README).',
      send: 'Invia',
      chipSummary: 'Riassunto',
      tplSummary: 'Riassumi "<documento>" in modo strutturato, con i punti chiave.',
      chipQuiz: 'Quiz',
      tplQuiz: 'Crea 10 domande di ripasso (con risposte) sui contenuti di "<documento>".',
      chipKeys: 'Punti chiave',
      tplKeys: 'Quali sono i concetti più importanti per l\'esame in "<documento>"?',
      chipFlash: 'Flashcard',
      tplFlash:
        'Crea 12 flashcard (fronte: domanda/termine, retro: risposta/definizione) da "<documento>".',
      chipOral: 'Esame orale',
      tplOral:
        'Fai il professore in un esame orale su "<documento>": fammi una domanda alla volta, aspetta la mia risposta, poi correggila e continua.',
      chipPlan: 'Piano di studio',
      tplPlan:
        'Crea un piano di studio usando i materiali indicizzati e le scadenze visibili. Argomento d\'esame: "<documento>".',
      chipWeek: 'Questa settimana',
      tplWeek: 'Riassumi i materiali del corso aggiunti questa settimana, documento per documento.',
      docPh: '<documento>',
    },
  };

  let uiLang = 'en';
  function t(key, ...args) {
    const v = (I18N[uiLang] && I18N[uiLang][key]) ?? I18N.en[key] ?? key;
    return typeof v === 'function' ? v(...args) : v;
  }
  const CHUNK_SIZE = 1200;
  const CHUNK_OVERLAP = 200;

  // -------------------------------------------------------------------------
  // pdf.js (caricato on-demand, vendorizzato nell'estensione)
  // -------------------------------------------------------------------------

  let pdfjsPromise = null;
  function loadPdfJs() {
    if (!pdfjsPromise) {
      pdfjsPromise = (async () => {
        const pdfjs = await import(chrome.runtime.getURL('vendor/pdf.min.mjs'));
        // Il worker non può essere creato direttamente da un URL
        // chrome-extension:// (vincolo same-origin dei Worker), quindi lo
        // carichiamo come Blob URL.
        try {
          const workerCode = await (await fetch(
            chrome.runtime.getURL('vendor/pdf.worker.min.mjs')
          )).blob();
          pdfjs.GlobalWorkerOptions.workerSrc = URL.createObjectURL(workerCode);
        } catch (_) {
          // fallback: pdf.js userà il "fake worker" sul main thread
          pdfjs.GlobalWorkerOptions.workerSrc = chrome.runtime.getURL(
            'vendor/pdf.worker.min.mjs'
          );
        }
        return pdfjs;
      })();
    }
    return pdfjsPromise;
  }

  // -------------------------------------------------------------------------
  // Rilevamento link ai materiali
  // -------------------------------------------------------------------------

  // Materiali scaricabili/leggibili direttamente
  const FILE_PATTERNS = [
    { re: /\/pluginfile\.php\//i, kind: 'file' },
    { re: /\/mod\/resource\/view\.php/i, kind: 'resource' },
    { re: /\/mod\/page\/view\.php/i, kind: 'page' },
    { re: /\.(pdf|pptx|docx)(\?|#|$)/i, kind: 'file' },
  ];
  // Contenitori da esplorare: sezioni del corso e cartelle Moodle
  const CONTAINER_PATTERNS = [
    { re: /\/mod\/folder\/view\.php/i, kind: 'folder' },
    { re: /\/course\/view\.php\?[^#]*\bsection=\d+/i, kind: 'section' },
    { re: /\/course\/section\.php\?/i, kind: 'section' },
  ];

  // Estrae i link da un albero DOM (la pagina corrente o una sottopagina
  // scaricata): baseUrl serve a risolvere gli href relativi nei documenti
  // creati con DOMParser, che non hanno un base URL proprio.
  function extractLinks(rootEl, baseUrl, excludes = []) {
    const materials = [];
    const containers = [];
    const seen = new Set();
    for (const a of rootEl.querySelectorAll('a[href]')) {
      const raw = a.getAttribute('href');
      if (!raw || raw.startsWith('#') || raw.startsWith('javascript:')) continue;
      let abs;
      try {
        abs = new URL(raw, baseUrl).href;
      } catch (_) {
        continue;
      }
      if (!abs.startsWith(location.origin)) continue; // solo same-origin
      const url = abs.split('#')[0];
      if (seen.has(url)) continue;
      const label =
        a.querySelector('.instancename')?.childNodes[0]?.textContent?.trim() ||
        a.textContent.trim().replace(/\s+/g, ' ').slice(0, 120) ||
        decodeURIComponent(url.split('/').pop().split('?')[0]);
      // lista di esclusione configurabile (es. file Teams/SharePoint)
      const lcUrl = url.toLowerCase();
      const lcLabel = label.toLowerCase();
      if (excludes.some((p) => p && (lcUrl.includes(p) || lcLabel.includes(p)))) continue;
      const fm = FILE_PATTERNS.find((p) => p.re.test(url));
      if (fm) {
        seen.add(url);
        materials.push({ url, kind: fm.kind, title: label });
        continue;
      }
      const cm = CONTAINER_PATTERNS.find((p) => p.re.test(url));
      if (cm && url !== location.href.split('#')[0]) {
        seen.add(url);
        containers.push({ url, kind: cm.kind, title: label });
      }
    }
    return { materials, containers };
  }

  // -------------------------------------------------------------------------
  // Fetch + estrazione testo
  // -------------------------------------------------------------------------

  // Hash del contenuto per la scansione incrementale: documenti identici
  // non vengono ri-parsati né ri-vettorizzati.
  async function sha256(data) {
    const buf = typeof data === 'string' ? new TextEncoder().encode(data) : data;
    const h = await crypto.subtle.digest('SHA-256', buf);
    return [...new Uint8Array(h)].map((b) => b.toString(16).padStart(2, '0')).join('');
  }

  function looksLikeLogin(finalUrl, html) {
    return (
      /\/login\//i.test(finalUrl) ||
      (html && /loginform|login\/index\.php/i.test(html.slice(0, 5000)))
    );
  }

  // Riconosce PDF/PPTX/DOCX dal content-type o, come ripiego (es.
  // application/octet-stream), dall'estensione nell'URL finale
  function guessBinaryKind(ctype, url) {
    if (ctype.includes('application/pdf') || /\.pdf(\?|#|$)/i.test(url)) return 'pdf';
    if (ctype.includes('presentationml') || /\.pptx(\?|#|$)/i.test(url)) return 'pptx';
    if (ctype.includes('wordprocessingml') || /\.docx(\?|#|$)/i.test(url)) return 'docx';
    return null;
  }

  async function fetchResource(item, condHeaders = {}) {
    const resp = await fetch(item.url, {
      credentials: 'include',
      redirect: 'follow',
      headers: condHeaders,
    });
    // 304 = il server conferma che il contenuto non è cambiato
    if (resp.status === 304) return { type: 'unchanged' };
    if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
    const ctype = (resp.headers.get('content-type') || '').toLowerCase();
    const validators = {
      etag: resp.headers.get('etag') || null,
      lastModified: resp.headers.get('last-modified') || null,
    };

    const binaryKind = guessBinaryKind(ctype, resp.url);
    if (binaryKind) {
      const buf = await resp.arrayBuffer();
      if (buf.byteLength > MAX_FILE_BYTES) throw new Error('File troppo grande, saltato');
      return { type: binaryKind, buf, finalUrl: resp.url, ...validators };
    }

    if (ctype.includes('text/html')) {
      const html = await resp.text();
      if (looksLikeLogin(resp.url, html)) {
        throw new Error('Sessione scaduta: effettua di nuovo il login su iCorsi');
      }
      const doc = new DOMParser().parseFromString(html, 'text/html');

      // mod/resource a volte restituisce una pagina HTML che incapsula il
      // file vero: cerchiamo il link/embed interno (workaround standard Moodle)
      if (item.kind === 'resource') {
        const inner =
          doc.querySelector('.resourceworkaround a[href]')?.href ||
          doc.querySelector('object[data]')?.getAttribute('data') ||
          doc.querySelector('iframe#resourceobject')?.src ||
          doc.querySelector('.resourcecontent a[href]')?.href;
        if (inner) {
          const innerUrl = new URL(inner, resp.url).href;
          if (innerUrl.startsWith(location.origin)) {
            const r2 = await fetch(innerUrl, { credentials: 'include' });
            const kind2 = r2.ok
              ? guessBinaryKind((r2.headers.get('content-type') || '').toLowerCase(), r2.url)
              : null;
            if (kind2) {
              const buf = await r2.arrayBuffer();
              if (buf.byteLength > MAX_FILE_BYTES) throw new Error('File troppo grande, saltato');
              return { type: kind2, buf, finalUrl: r2.url, ...validators };
            }
          }
        }
        throw new Error('Formato non supportato (gestiti: PDF, PPTX, DOCX, pagine)');
      }

      // mod/page: estraiamo il testo del contenuto principale
      const main =
        doc.querySelector('#region-main') ||
        doc.querySelector('[role="main"]') ||
        doc.body;
      main.querySelectorAll('script, style, nav, footer, .activity-navigation')
        .forEach((el) => el.remove());
      const text = main.innerText.replace(/\n{3,}/g, '\n\n').trim();
      return { type: 'html', text, finalUrl: resp.url, ...validators };
    }

    throw new Error(`Tipo di contenuto non supportato: ${ctype.split(';')[0] || 'sconosciuto'}`);
  }

  async function extractPdfText(buf) {
    const pdfjs = await loadPdfJs();
    const pdf = await pdfjs.getDocument({ data: buf }).promise;
    const pages = [];
    let totalChars = 0;
    for (let p = 1; p <= pdf.numPages; p++) {
      const page = await pdf.getPage(p);
      const content = await page.getTextContent();
      const text = content.items
        .map((it) => it.str)
        .join(' ')
        .replace(/\s+/g, ' ')
        .trim();
      totalChars += text.length;
      pages.push({ page: p, text });
    }
    const probablyScanned = pdf.numPages > 0 && totalChars / pdf.numPages < 40;
    await pdf.destroy();
    return { pages, numPages: pdf.numPages, probablyScanned };
  }

  // -------------------------------------------------------------------------
  // PPTX / DOCX — sono archivi ZIP di XML: niente librerie esterne, basta un
  // mini-lettore ZIP con DecompressionStream (nativo nel browser)
  // -------------------------------------------------------------------------

  async function unzip(buf, nameFilter) {
    const view = new DataView(buf);
    const bytes = new Uint8Array(buf);

    // End Of Central Directory: si cerca la firma dal fondo del file
    let eocd = -1;
    const stop = Math.max(0, buf.byteLength - 22 - 65536);
    for (let i = buf.byteLength - 22; i >= stop; i--) {
      if (view.getUint32(i, true) === 0x06054b50) {
        eocd = i;
        break;
      }
    }
    if (eocd < 0) throw new Error('archivio ZIP non valido');

    const count = view.getUint16(eocd + 10, true);
    let off = view.getUint32(eocd + 16, true);
    const files = new Map();
    for (let n = 0; n < count; n++) {
      if (view.getUint32(off, true) !== 0x02014b50) break;
      const method = view.getUint16(off + 10, true);
      const compSize = view.getUint32(off + 20, true);
      const nameLen = view.getUint16(off + 28, true);
      const extraLen = view.getUint16(off + 30, true);
      const commentLen = view.getUint16(off + 32, true);
      const localOff = view.getUint32(off + 42, true);
      const name = new TextDecoder().decode(bytes.subarray(off + 46, off + 46 + nameLen));
      off += 46 + nameLen + extraLen + commentLen;

      if (!nameFilter(name)) continue; // si decomprime solo il necessario
      // l'header locale può avere lunghezze extra diverse dal central directory
      const lnl = view.getUint16(localOff + 26, true);
      const lel = view.getUint16(localOff + 28, true);
      const dataStart = localOff + 30 + lnl + lel;
      const comp = bytes.subarray(dataStart, dataStart + compSize);
      if (method === 0) {
        files.set(name, comp); // non compresso
      } else if (method === 8) {
        const stream = new Blob([comp]).stream().pipeThrough(
          new DecompressionStream('deflate-raw')
        );
        files.set(name, new Uint8Array(await new Response(stream).arrayBuffer()));
      }
    }
    return files;
  }

  function xmlTexts(xmlBytes, localName) {
    const xml = new TextDecoder().decode(xmlBytes);
    const doc = new DOMParser().parseFromString(xml, 'application/xml');
    return [...doc.getElementsByTagNameNS('*', localName)];
  }

  // DOCX: il testo vive in word/document.xml, paragrafi <w:p> con run <w:t>
  async function extractDocxText(buf) {
    const files = await unzip(buf, (n) => n === 'word/document.xml');
    const docXml = files.get('word/document.xml');
    if (!docXml) throw new Error('DOCX senza word/document.xml');
    const paras = xmlTexts(docXml, 'p')
      .map((p) =>
        [...p.getElementsByTagNameNS('*', 't')].map((t) => t.textContent).join('')
      )
      .filter((s) => s.trim());
    return paras.join('\n');
  }

  // PPTX: una slide = ppt/slides/slideN.xml; il testo è negli elementi <a:t>.
  // Ritorna pagine numerate come i PDF, così le citazioni dicono la slide.
  async function extractPptxText(buf) {
    const isSlide = (n) => /^ppt\/slides\/slide\d+\.xml$/.test(n);
    const files = await unzip(buf, isSlide);
    const slideNum = (n) => parseInt(n.match(/slide(\d+)\.xml$/)[1], 10);
    const names = [...files.keys()].sort((a, b) => slideNum(a) - slideNum(b));
    return names.map((name) => ({
      page: slideNum(name),
      text: xmlTexts(files.get(name), 't')
        .map((t) => t.textContent)
        .join(' ')
        .replace(/\s+/g, ' ')
        .trim(),
    }));
  }

  // -------------------------------------------------------------------------
  // Chunking
  // -------------------------------------------------------------------------

  function chunkString(text, meta) {
    const chunks = [];
    let start = 0;
    while (start < text.length) {
      let end = Math.min(start + CHUNK_SIZE, text.length);
      // prova a tagliare su un confine di frase
      if (end < text.length) {
        const cut = text.lastIndexOf('. ', end);
        if (cut > start + CHUNK_SIZE * 0.5) end = cut + 1;
      }
      const piece = text.slice(start, end).trim();
      if (piece.length > 50) chunks.push({ ...meta, text: piece });
      if (end >= text.length) break;
      start = end - CHUNK_OVERLAP;
    }
    return chunks;
  }

  function chunkPdf(pages, meta) {
    const chunks = [];
    for (const { page, text } of pages) {
      if (!text) continue;
      chunks.push(...chunkString(text, { ...meta, page }));
    }
    return chunks;
  }

  function hashId(s) {
    let h = 5381;
    for (let i = 0; i < s.length; i++) h = ((h << 5) + h + s.charCodeAt(i)) >>> 0;
    return 'doc_' + h.toString(16);
  }

  // -------------------------------------------------------------------------
  // Indicizzazione della pagina corrente (sezioni del corso)
  // -------------------------------------------------------------------------

  function extractCurrentPageChunks() {
    const chunks = [];
    const title = document.title.replace(/\s*\|.*$/, '').trim() || 'Pagina corso';
    const docId = hashId(location.href.split('#')[0]);
    const meta = { docId, title, url: location.href.split('#')[0], page: null };

    // 1) sezioni del corso, con il nome come metadato (utile nelle citazioni)
    const sections = [...document.querySelectorAll('li.section, .course-section')];
    const covered = [];
    for (const sec of sections) {
      const name =
        sec.querySelector('.sectionname, h3, h2')?.textContent?.trim() || '';
      const text = sec.innerText.replace(/\s+\n/g, '\n').trim();
      if (text.length > 80) {
        chunks.push(...chunkString(text, { ...meta, section: name || null }));
        covered.push(sec);
      }
    }

    // 2) tutto il resto della pagina (intro del corso, annunci, blocchi
    //    laterali, pagine senza struttura a sezioni): si legge l'intero
    //    contenuto principale, nascondendo temporaneamente le sezioni già
    //    coperte per non duplicarle (innerText ignora gli elementi nascosti;
    //    lo stile viene ripristinato subito, senza repaint visibile)
    const main =
      document.querySelector('#region-main, [role="main"], #page-content, #page') ||
      document.body;
    const prevDisplay = covered.map((s) => s.style.display);
    covered.forEach((s) => (s.style.display = 'none'));
    let rest = '';
    try {
      rest = main.innerText.replace(/\n{3,}/g, '\n\n').trim();
    } finally {
      covered.forEach((s, i) => (s.style.display = prevDisplay[i]));
    }
    if (rest.length > 80) {
      chunks.push(...chunkString(rest, meta));
    }

    return { doc: { id: docId, title, url: meta.url, kind: 'coursepage' }, chunks };
  }

  // -------------------------------------------------------------------------
  // Pipeline di scansione
  // -------------------------------------------------------------------------

  // Scadenze ed eventi visibili sulla pagina (blocchi timeline/calendario di
  // Moodle): passati al modello come contesto per domande tipo
  // "cosa devo studiare per venerdì?"
  function collectDeadlines() {
    let text = '';
    for (const sel of [
      '.block_timeline', '.block_calendar_upcoming',
      '[data-block="timeline"]', '[data-block="calendar_upcoming"]',
    ]) {
      for (const elr of document.querySelectorAll(sel)) {
        text += elr.innerText.trim() + '\n';
      }
    }
    return text.trim().slice(0, 1500);
  }

  function sendBg(msg) {
    return new Promise((resolve) =>
      chrome.runtime.sendMessage(msg, (resp) => {
        if (chrome.runtime.lastError) {
          resolve({ ok: false, error: chrome.runtime.lastError.message });
        } else {
          resolve(resp);
        }
      })
    );
  }

  async function indexInBackground(doc, chunks) {
    const resp = await sendBg({ type: 'INDEX_DOC', doc, chunks });
    if (!resp?.ok) {
      throw new Error(`indicizzazione fallita: ${resp?.error || 'nessuna risposta dal background'}`);
    }
  }

  const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

  async function scanPage(onProgress) {
    const report = { indexed: 0, unchanged: 0, skipped: [], warnings: [] };
    const { excludePatterns, deepScan } = await chrome.storage.local.get([
      'excludePatterns', 'deepScan',
    ]);
    const excludes = (excludePatterns ?? DEFAULT_EXCLUDES)
      .split('\n')
      .map((s) => s.trim().toLowerCase())
      .filter(Boolean);

    // 0. pulizia retroattiva: i documenti già indicizzati che ora ricadono
    //    nella lista di esclusione vengono rimossi dall'indice
    try {
      const purge = await sendBg({ type: 'REMOVE_MATCHING', patterns: excludes });
      if (purge?.removed?.length > 0) {
        report.warnings.push(t('removedExcluded', purge.removed.length, purge.removed.join('", "')));
      }
    } catch (_) { /* non bloccante */ }

    // 1. testo visibile della pagina corrente
    onProgress(t('statusScanPage'));
    try {
      const pageData = extractCurrentPageChunks();
      if (pageData.chunks.length > 0) {
        const pageHash = await sha256(pageData.chunks.map((c) => c.text).join('\n'));
        const chk = await sendBg({ type: 'CHECK_DOC', docId: pageData.doc.id, contentHash: pageHash });
        if (chk?.unchanged) {
          report.unchanged++;
        } else {
          pageData.doc.contentHash = pageHash;
          await indexInBackground(pageData.doc, pageData.chunks);
          report.indexed++;
        }
      } else {
        report.warnings.push(t('warnNoPageText'));
      }
    } catch (e) {
      report.skipped.push(`${t('currentPage')} — ${e.message}`);
    }

    // 2. link della pagina corrente + esplorazione delle sottopagine
    //    (sezioni del corso e cartelle): i materiali trovati lì dentro
    //    si aggiungono alla coda, il testo delle sezioni viene indicizzato
    const found = extractLinks(document, location.href, excludes);
    const materials = found.materials;
    // L'esplorazione delle sottopagine è opt-in: di default si analizzano
    // solo i documenti visibili sulla dashboard del corso
    const containers = deepScan === true ? found.containers.slice(0, MAX_SUBPAGES) : [];
    if (deepScan === true && found.containers.length > MAX_SUBPAGES) {
      report.warnings.push(t('warnSubpages', found.containers.length, MAX_SUBPAGES));
    }

    for (const cont of containers) {
      onProgress(t(cont.kind === 'folder' ? 'statusExploreFolder' : 'statusExploreSection', cont.title));
      try {
        const resp = await fetch(cont.url, { credentials: 'include', redirect: 'follow' });
        if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
        const html = await resp.text();
        if (looksLikeLogin(resp.url, html)) {
          throw new Error('Sessione scaduta: effettua di nuovo il login su iCorsi');
        }
        const sub = new DOMParser().parseFromString(html, 'text/html');

        // materiali linkati nella sottopagina
        const subLinks = extractLinks(sub, resp.url, excludes);
        for (const m of subLinks.materials) {
          if (!materials.some((x) => x.url === m.url)) materials.push(m);
        }

        // testo delle sezioni (le cartelle sono solo elenchi di file)
        if (cont.kind === 'section') {
          const main = sub.querySelector('#region-main, [role="main"]') || sub.body;
          main.querySelectorAll('script, style, nav, footer').forEach((n) => n.remove());
          const text = (main.innerText || main.textContent || '')
            .replace(/\n{3,}/g, '\n\n')
            .trim();
          if (text.length > 80) {
            const docId = hashId(cont.url);
            const contentHash = await sha256(text);
            const chk = await sendBg({ type: 'CHECK_DOC', docId, contentHash });
            if (chk?.unchanged) {
              report.unchanged++;
            } else {
              const chunks = chunkString(text, {
                docId, title: cont.title, url: cont.url, page: null,
              });
              if (chunks.length > 0) {
                await indexInBackground(
                  { id: docId, title: cont.title, url: cont.url, kind: 'coursepage', contentHash },
                  chunks
                );
                report.indexed++;
              }
            }
          }
        }
      } catch (e) {
        report.skipped.push(`${cont.title} — ${e.message}`);
      }
      await sleep(FETCH_DELAY_MS);
    }

    let links = materials;
    if (links.length > MAX_DOCS_PER_SCAN) {
      report.warnings.push(t('warnTooMany', links.length, MAX_DOCS_PER_SCAN));
      links = links.slice(0, MAX_DOCS_PER_SCAN);
    }
    onProgress(t('statusFound', links.length));

    let done = 0;
    const queue = [...links];
    async function worker() {
      while (queue.length > 0) {
        const item = queue.shift();
        done++;
        onProgress(`(${done}/${links.length}) ${item.title}`);
        try {
          const docId = hashId(item.url);

          // scansione incrementale, livello 1: validatori HTTP del server
          const prev = await sendBg({ type: 'GET_DOC', docId });
          const condHeaders = {};
          if (prev?.doc?.etag) condHeaders['If-None-Match'] = prev.doc.etag;
          if (prev?.doc?.lastModified) condHeaders['If-Modified-Since'] = prev.doc.lastModified;

          const res = await fetchResource(item, condHeaders);
          if (res.type === 'unchanged') {
            report.unchanged++;
          } else {
            // livello 2: hash del contenuto (se il server non supporta i 304,
            // si evita comunque il costo di parsing + embeddings)
            const contentHash = await sha256(res.buf || res.text);
            const chk = await sendBg({ type: 'CHECK_DOC', docId, contentHash });
            if (chk?.unchanged) {
              report.unchanged++;
            } else {
              let chunks = [];
              const doc = {
                id: docId,
                title: item.title,
                url: item.url,
                kind: res.type,
                contentHash,
                etag: res.etag || null,
                lastModified: res.lastModified || null,
              };
              if (res.type === 'pdf') {
                const { pages, numPages, probablyScanned } = await extractPdfText(res.buf);
                if (probablyScanned) {
                  report.warnings.push(t('warnScanned', item.title));
                }
                doc.pages = numPages;
                chunks = chunkPdf(pages, { docId, title: item.title, url: item.url });
              } else if (res.type === 'pptx') {
                const pages = await extractPptxText(res.buf);
                doc.pages = pages.length;
                chunks = chunkPdf(pages, { docId, title: item.title, url: item.url });
              } else if (res.type === 'docx') {
                const text = await extractDocxText(res.buf);
                chunks = chunkString(text, { docId, title: item.title, url: item.url, page: null });
              } else if (res.type === 'html') {
                chunks = chunkString(res.text, { docId, title: item.title, url: item.url, page: null });
              }
              if (chunks.length > 0) {
                await indexInBackground(doc, chunks);
                report.indexed++;
              } else {
                report.skipped.push(`${item.title} (${t('warnNoPageText')})`);
              }
            }
          }
        } catch (e) {
          report.skipped.push(`${item.title} — ${e.message}`);
        }
        await sleep(FETCH_DELAY_MS);
      }
    }
    await Promise.all(Array.from({ length: FETCH_CONCURRENCY }, worker));
    return report;
  }

  // -------------------------------------------------------------------------
  // Mini-renderer Markdown (DOM-safe: niente innerHTML, quindi niente XSS
  // anche se il modello ricopiasse testo ostile dalla pagina).
  // Supporta: titoli, liste, blocchi di codice, **grassetto**, *corsivo*,
  // `codice`, [testo](url) e citazioni [n] linkate alle fonti.
  // -------------------------------------------------------------------------

  function mkLink(href, text) {
    const a = document.createElement('a');
    a.href = href;
    a.target = '_blank';
    a.rel = 'noopener';
    a.textContent = text;
    return a;
  }

  function appendInline(node, text, sources) {
    const re =
      /(`[^`\n]+`)|(\*\*[^*\n]+\*\*)|(\*[^*\n]+\*)|\[([^\]\n]+)\]\((https?:\/\/[^\s)]+)\)|(\[(\d{1,2})\])/g;
    let last = 0;
    let m;
    while ((m = re.exec(text))) {
      if (m.index > last) node.appendChild(document.createTextNode(text.slice(last, m.index)));
      if (m[1]) {
        const c = document.createElement('code');
        c.textContent = m[1].slice(1, -1);
        node.appendChild(c);
      } else if (m[2]) {
        const b = document.createElement('strong');
        b.textContent = m[2].slice(2, -2);
        node.appendChild(b);
      } else if (m[3]) {
        const i2 = document.createElement('em');
        i2.textContent = m[3].slice(1, -1);
        node.appendChild(i2);
      } else if (m[4] && m[5]) {
        node.appendChild(mkLink(m[5], m[4]));
      } else if (m[6]) {
        const n = parseInt(m[7], 10);
        const src = sources && sources.find((s) => s.n === n);
        if (src) {
          // ancora #page=N: il viewer PDF di Chrome apre alla pagina citata
          const a = mkLink(src.page ? `${src.url}#page=${src.page}` : src.url, `[${n}]`);
          a.className = 'ica-cite';
          a.title = src.title + (src.page ? ` — ${t('pageAbbr')} ${src.page}` : '');
          node.appendChild(a);
        } else {
          node.appendChild(document.createTextNode(m[6]));
        }
      }
      last = re.lastIndex;
    }
    if (last < text.length) node.appendChild(document.createTextNode(text.slice(last)));
  }

  function mdToFragment(md, sources) {
    const frag = document.createDocumentFragment();
    const lines = md.split('\n');
    let i = 0;
    let listEl = null;
    let listType = null;
    const flushList = () => {
      listEl = null;
      listType = null;
    };
    const isSpecial = (l) =>
      /^(#{1,4}\s|```|\s*[-*•]\s+|\s*\d+[.)]\s+)/.test(l);

    while (i < lines.length) {
      const line = lines[i];

      if (/^```/.test(line)) {
        const buf = [];
        i++;
        while (i < lines.length && !/^```/.test(lines[i])) buf.push(lines[i++]);
        i++; // fence di chiusura
        const pre = document.createElement('pre');
        const code = document.createElement('code');
        code.textContent = buf.join('\n');
        pre.appendChild(code);
        frag.appendChild(pre);
        flushList();
        continue;
      }

      const h = line.match(/^(#{1,4})\s+(.*)/);
      if (h) {
        const hEl = document.createElement('h' + Math.min(h[1].length + 2, 6));
        appendInline(hEl, h[2], sources);
        frag.appendChild(hEl);
        flushList();
        i++;
        continue;
      }

      const ul = line.match(/^\s*[-*•]\s+(.*)/);
      const ol = line.match(/^\s*\d+[.)]\s+(.*)/);
      if (ul || ol) {
        const type = ul ? 'ul' : 'ol';
        if (!listEl || listType !== type) {
          listEl = document.createElement(type);
          frag.appendChild(listEl);
          listType = type;
        }
        const li = document.createElement('li');
        appendInline(li, ul ? ul[1] : ol[1], sources);
        listEl.appendChild(li);
        i++;
        continue;
      }

      if (!line.trim()) {
        flushList();
        i++;
        continue;
      }

      // paragrafo: accorpa le righe consecutive non speciali
      const buf = [line];
      i++;
      while (i < lines.length && lines[i].trim() && !isSpecial(lines[i])) buf.push(lines[i++]);
      const p = document.createElement('p');
      appendInline(p, buf.join(' '), sources);
      frag.appendChild(p);
      flushList();
    }
    return frag;
  }

  function renderMarkdown(container, text, sources) {
    container.textContent = '';
    container.appendChild(mdToFragment(text, sources));
  }

  // -------------------------------------------------------------------------
  // Sidebar UI (Shadow DOM)
  // -------------------------------------------------------------------------

  async function buildSidebar() {
    const host = document.createElement('div');
    host.id = 'icorsi-assistant-host';
    document.documentElement.appendChild(host);
    const root = host.attachShadow({ mode: 'open' });

    const css = await (await fetch(chrome.runtime.getURL('src/sidebar.css'))).text();
    const style = document.createElement('style');
    style.textContent = css;
    root.appendChild(style);

    const { uiLang: savedLang } = await chrome.storage.local.get(['uiLang']);
    if (savedLang && I18N[savedLang]) uiLang = savedLang;

    root.appendChild(buildDom());
    applyLang(root);
    wireUp(root);
  }

  function el(tag, attrs = {}, children = []) {
    const node = document.createElement(tag);
    for (const [k, v] of Object.entries(attrs)) {
      if (k === 'text') node.textContent = v;
      else if (k === 'html') node.innerHTML = v;
      else node.setAttribute(k, v);
    }
    for (const c of children) node.appendChild(c);
    return node;
  }

  function buildDom() {
    const frag = document.createDocumentFragment();

    frag.appendChild(el('button', { id: 'ica-fab', 'data-i18n-title': 'fabTitle', text: 'AI' }));

    const panel = el('div', { id: 'ica-panel', class: 'hidden' });
    panel.appendChild(
      el('div', { class: 'ica-header' }, [
        el('span', { class: 'ica-title', 'data-i18n': 'appTitle' }),
        el('button', { id: 'ica-uilang', title: 'Language / Lingua', text: 'EN' }),
        el('button', { id: 'ica-settings-btn', 'data-i18n': 'settingsTitle' }),
        el('button', { id: 'ica-close', 'data-i18n-title': 'close', text: '×' }),
      ])
    );

    const settings = el('div', { id: 'ica-settings', class: 'hidden' });
    settings.appendChild(
      el('div', { class: 'ica-settings-inner' }, [
        el('label', { 'data-i18n': 'urlLabel' }),
        el('input', { id: 'ica-ollama-url', type: 'text', placeholder: 'http://localhost:11434' }),
        el('label', { 'data-i18n': 'modelLabel' }),
        el('div', { class: 'ica-settings-row' }, [
          (() => {
            const sel = el('select', { id: 'ica-model' });
            sel.appendChild(el('option', { value: '', 'data-i18n': 'modelNone' }));
            return sel;
          })(),
          el('button', { id: 'ica-refresh-models', class: 'ica-btn', 'data-i18n-title': 'refreshTitle', text: '↻' }),
        ]),
        el('label', { 'data-i18n': 'langLabel' }),
        (() => {
          const sel = el('select', { id: 'ica-lang' });
          sel.appendChild(el('option', { value: '', 'data-i18n': 'langAuto' }));
          for (const [v, label] of [
            ['en', 'English'], ['it', 'Italiano'], ['de', 'Deutsch'], ['fr', 'Français'],
          ]) {
            sel.appendChild(el('option', { value: v, text: label }));
          }
          return sel;
        })(),
        el('label', { class: 'ica-check' }, [
          el('input', { id: 'ica-autoscan', type: 'checkbox' }),
          el('span', { 'data-i18n': 'autoScanLabel' }),
        ]),
        el('label', { class: 'ica-check' }, [
          el('input', { id: 'ica-deepscan', type: 'checkbox' }),
          el('span', { 'data-i18n': 'deepScanLabel' }),
        ]),
        el('label', { 'data-i18n': 'excludeLabel' }),
        el('textarea', { id: 'ica-exclude', rows: '3' }),
        el('p', { class: 'ica-privacy', 'data-i18n': 'privacy' }),
        el('p', { id: 'ica-embed-status', class: 'ica-privacy', text: '' }),
        el('div', { class: 'ica-settings-row' }, [
          el('button', { id: 'ica-save-settings', class: 'ica-btn', 'data-i18n': 'save' }),
          el('button', { id: 'ica-clear-index', class: 'ica-btn ica-danger', 'data-i18n': 'clearIndex' }),
        ]),
      ])
    );
    panel.appendChild(settings);

    panel.appendChild(
      el('div', { class: 'ica-toolbar' }, [
        el('button', { id: 'ica-scan', class: 'ica-btn ica-primary', 'data-i18n': 'scan' }),
        el('span', { id: 'ica-stats', text: '' }),
      ])
    );
    panel.appendChild(el('div', { id: 'ica-status', text: '' }));
    panel.appendChild(el('div', { id: 'ica-messages' }));

    const chips = [
      ['chipSummary', 'tplSummary'],
      ['chipQuiz', 'tplQuiz'],
      ['chipKeys', 'tplKeys'],
      ['chipFlash', 'tplFlash'],
      ['chipOral', 'tplOral'],
      ['chipPlan', 'tplPlan'],
    ].map(([labelKey, tplKey]) =>
      el('button', { class: 'ica-chip', 'data-i18n': labelKey, 'data-tplkey': tplKey })
    );
    chips.push(
      el('button', { class: 'ica-chip', 'data-i18n': 'chipWeek', 'data-action': 'weekly' })
    );
    panel.appendChild(el('div', { class: 'ica-quick' }, chips));

    panel.appendChild(
      el('div', { class: 'ica-inputrow' }, [
        el('textarea', { id: 'ica-input', rows: '2', 'data-i18n-ph': 'placeholder' }),
        el('button', { id: 'ica-send', class: 'ica-btn ica-primary', 'data-i18n-title': 'send', text: '→' }),
      ])
    );
    frag.appendChild(panel);
    return frag;
  }

  // Applica (o ri-applica) le etichette dell'interfaccia nella lingua corrente
  function applyLang(root) {
    for (const node of root.querySelectorAll('[data-i18n]')) {
      node.textContent = t(node.getAttribute('data-i18n'));
    }
    for (const node of root.querySelectorAll('[data-i18n-title]')) {
      node.title = t(node.getAttribute('data-i18n-title'));
    }
    for (const node of root.querySelectorAll('[data-i18n-ph]')) {
      node.placeholder = t(node.getAttribute('data-i18n-ph'));
    }
    const langBtn = root.querySelector('#ica-uilang');
    if (langBtn) langBtn.textContent = uiLang.toUpperCase();
  }

  function wireUp(root) {
    const $ = (sel) => root.querySelector(sel);
    const panel = $('#ica-panel');
    const messages = $('#ica-messages');
    const status = $('#ica-status');
    const input = $('#ica-input');

    // URL della fonte: per i PDF con pagina nota si aggiunge #page=N, che il
    // viewer PDF di Chrome rispetta (apre direttamente alla pagina citata)
    function sourceHref(s) {
      return s.page ? `${s.url}#page=${s.page}` : s.url;
    }

    function attachSources(wrap, sources) {
      if (!sources || sources.length === 0) return;
      const list = el('div', { class: 'ica-sources' });
      list.appendChild(el('div', { class: 'ica-sources-title', text: t('sourcesLabel') }));
      for (const s of sources) {
        const loc = s.page ? `${t('pageAbbr')} ${s.page}` : s.section || '';
        const a = el('a', {
          href: sourceHref(s),
          target: '_blank',
          rel: 'noopener',
          text: `[${s.n}] ${s.title}${loc ? ' — ' + loc : ''}`,
        });
        list.appendChild(a);
      }
      wrap.appendChild(list);
    }

    function addMsg(role, text, sources) {
      const wrap = el('div', { class: `ica-msg ica-${role}` });
      const body = el('div', { class: 'ica-msg-body' });
      body.textContent = text;
      wrap.appendChild(body);
      attachSources(wrap, sources);
      messages.appendChild(wrap);
      messages.scrollTop = messages.scrollHeight;
      return wrap;
    }

    async function refreshStats() {
      const r = await sendBg({ type: 'GET_STATS' });
      if (r?.ok) {
        $('#ica-stats').textContent = t('statsFmt', r.docs, r.chunks);
      }
    }

    $('#ica-fab').addEventListener('click', () => {
      panel.classList.toggle('hidden');
      refreshStats();
    });
    $('#ica-close').addEventListener('click', () => panel.classList.add('hidden'));

    async function refreshModels(selected) {
      const sel = $('#ica-model');
      const url = $('#ica-ollama-url').value.trim();
      const r = await sendBg({ type: 'LIST_MODELS', ollamaUrl: url || undefined });
      // ricostruisce la lista mantenendo l'opzione "solo estrattiva"
      sel.replaceChildren(el('option', { value: '', text: t('modelNone') }));
      if (r?.ok && r.models.length > 0) {
        for (const m of r.models) sel.appendChild(el('option', { value: m, text: m }));
        if (selected) sel.value = selected;
        status.textContent = t('ollamaOk', r.models.length);
        const hasEmbed = r.models.some((m) => m.startsWith('nomic-embed-text'));
        $('#ica-embed-status').textContent = hasEmbed ? t('embedOn') : t('embedOff');
      } else {
        if (selected) {
          // mantiene il modello salvato anche se Ollama ora non risponde
          sel.appendChild(el('option', { value: selected, text: selected }));
          sel.value = selected;
        }
        status.textContent = t('ollamaDown');
      }
      setTimeout(() => (status.textContent = ''), 5000);
    }

    // pulsante lingua interfaccia: alterna tra le lingue disponibili
    $('#ica-uilang').addEventListener('click', async () => {
      const langs = Object.keys(I18N);
      uiLang = langs[(langs.indexOf(uiLang) + 1) % langs.length];
      await chrome.storage.local.set({ uiLang });
      applyLang(root);
      refreshStats();
    });

    $('#ica-settings-btn').addEventListener('click', async () => {
      const box = $('#ica-settings');
      box.classList.toggle('hidden');
      if (!box.classList.contains('hidden')) {
        const saved = await chrome.storage.local.get([
          'ollamaUrl', 'model', 'answerLang', 'autoScan', 'excludePatterns',
        ]);
        $('#ica-ollama-url').value = saved.ollamaUrl || 'http://localhost:11434';
        $('#ica-lang').value = saved.answerLang || '';
        $('#ica-autoscan').checked = saved.autoScan !== false; // default: attivo
        $('#ica-deepscan').checked = saved.deepScan === true;  // default: spento
        $('#ica-exclude').value = saved.excludePatterns ?? DEFAULT_EXCLUDES;
        await refreshModels(saved.model || '');
      }
    });

    $('#ica-refresh-models').addEventListener('click', () =>
      refreshModels($('#ica-model').value)
    );

    $('#ica-save-settings').addEventListener('click', async () => {
      await chrome.storage.local.set({
        ollamaUrl: $('#ica-ollama-url').value.trim() || 'http://localhost:11434',
        model: $('#ica-model').value,
        answerLang: $('#ica-lang').value,
        autoScan: $('#ica-autoscan').checked,
        deepScan: $('#ica-deepscan').checked,
        excludePatterns: $('#ica-exclude').value,
      });
      status.textContent = t('saved');
      setTimeout(() => (status.textContent = ''), 2000);
    });

    $('#ica-clear-index').addEventListener('click', async () => {
      if (!confirm(t('confirmClear'))) return;
      await sendBg({ type: 'CLEAR_INDEX' });
      refreshStats();
      status.textContent = t('cleared');
      setTimeout(() => (status.textContent = ''), 2000);
    });

    async function doScan(silent) {
      const btn = $('#ica-scan');
      if (btn.disabled) return;
      btn.disabled = true;
      try {
        const report = await scanPage((s) => (status.textContent = s));
        status.textContent = '';
        let txt = t('scanDone', report.indexed, report.unchanged);
        if (report.skipped.length > 0) {
          txt += `\n\n${t('skippedLabel', report.skipped.length)}\n• ` + report.skipped.join('\n• ');
        }
        if (report.warnings.length > 0) {
          txt += `\n\n${t('warningsLabel')}\n• ` + report.warnings.join('\n• ');
        }
        // in modalità automatica il report compare in chat solo se c'è
        // qualcosa di nuovo, per non riempire la chat a ogni cambio pagina
        if (!silent || report.indexed > 0) addMsg('assistant', txt);
        refreshStats();
      } catch (e) {
        if (!silent) addMsg('assistant', t('scanError', e.message));
      } finally {
        btn.disabled = false;
      }
    }
    $('#ica-scan').addEventListener('click', () => doScan(false));

    // Comandi rapidi: inseriscono il template nell'input con il segnaposto
    // documento già selezionato; "This week" parte direttamente
    for (const chip of root.querySelectorAll('.ica-chip')) {
      chip.addEventListener('click', () => {
        if (chip.getAttribute('data-action') === 'weekly') {
          ask(t('tplWeek'), { weekly: true });
          return;
        }
        const tpl = t(chip.getAttribute('data-tplkey'));
        input.value = tpl;
        input.focus();
        const ph = t('docPh');
        const start = tpl.indexOf(ph);
        if (start >= 0) input.setSelectionRange(start, start + ph.length);
      });
    }

    // cronologia della conversazione (per dare memoria al modello) con
    // persistenza per pagina: sopravvive ai ricaricamenti nello stesso tab
    const CHAT_KEY = 'ica-chat:' + location.href.split('#')[0];
    const chatHistory = [];
    try {
      const saved = JSON.parse(sessionStorage.getItem(CHAT_KEY) || '[]');
      for (const m of saved) {
        if (!m || typeof m.content !== 'string') continue;
        chatHistory.push({ role: m.role, content: m.content });
        if (m.role === 'assistant') {
          const wrap = addMsg('assistant', '');
          renderMarkdown(wrap.querySelector('.ica-msg-body'), m.content, null);
        } else {
          addMsg('user', m.content);
        }
      }
    } catch (_) { /* cronologia corrotta: si riparte da zero */ }

    function saveChat() {
      try {
        sessionStorage.setItem(CHAT_KEY, JSON.stringify(chatHistory));
      } catch (_) { /* quota piena: pazienza, la chat resta solo in memoria */ }
    }

    function ask(presetQ, opts = {}) {
      const q = (presetQ ?? input.value).trim();
      if (!q) return;
      if (!presetQ) input.value = '';
      addMsg('user', q);
      const pending = addMsg('assistant', t('searching'));
      const body = pending.querySelector('.ica-msg-body');
      // la cronologia inviata NON include il messaggio corrente
      const historyToSend = chatHistory.slice(-6);

      let streamed = '';
      let finished = false;

      const finalize = (r) => {
        if (finished) return;
        finished = true;
        const answerText = r.answer || streamed || t('noAnswer');
        // durante lo streaming il testo resta semplice; a risposta completa
        // viene formattato in Markdown con citazioni [n] cliccabili
        renderMarkdown(body, answerText, r.sources);
        attachSources(pending, r.sources);
        messages.scrollTop = messages.scrollHeight;
        chatHistory.push({ role: 'user', content: q });
        chatHistory.push({ role: 'assistant', content: answerText });
        if (chatHistory.length > 12) chatHistory.splice(0, chatHistory.length - 12);
        saveChat();
      };

      let port;
      try {
        port = chrome.runtime.connect({ name: 'ica-ask' });
      } catch (e) {
        finalize({ answer: t('errGeneric', e.message), sources: [] });
        return;
      }

      port.onMessage.addListener((m) => {
        if (m.type === 'delta') {
          if (!streamed) body.textContent = ''; // rimuove il placeholder
          streamed += m.text;
          body.textContent = streamed;
          messages.scrollTop = messages.scrollHeight;
        } else if (m.type === 'done') {
          finalize(m);
          port.disconnect();
        }
      });
      port.onDisconnect.addListener(() => {
        if (!finished) {
          finalize({ answer: streamed || t('errConn'), sources: [] });
        }
      });

      port.postMessage({
        question: q,
        history: historyToSend,
        weekly: !!opts.weekly,
        pageContext: collectDeadlines(),
      });
    }

    $('#ica-send').addEventListener('click', () => ask());
    input.addEventListener('keydown', (e) => {
      if (e.key === 'Enter' && !e.shiftKey) {
        e.preventDefault();
        ask();
      }
    });

    refreshStats();

    // Scansione automatica SOLO sulla dashboard del corso (course/view.php
    // senza parametro section): le altre pagine si scansionano solo a mano.
    // Disattivabile nelle impostazioni; economica grazie all'indice
    // incrementale.
    const isCourseDashboard =
      /\/course\/view\.php$/.test(location.pathname) &&
      !/[?&]section=\d/.test(location.search);
    chrome.storage.local.get(['autoScan']).then(({ autoScan }) => {
      if (autoScan !== false && isCourseDashboard) setTimeout(() => doScan(true), 1500);
    });
  }

  buildSidebar().catch((e) =>
    console.error('[iCorsi Assistant] errore inizializzazione sidebar:', e)
  );
})();
